version: '3'

services:
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: myapp/app
    container_name: app
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


